web:
  build: .
  volumes:
    - .:/orator-club
  ports:
    - "3000:3000"
  links:
    - db
  env_file:
    - '.env.web'
db:
  image: postgres:9.4.1
  ports:
    - "5432:5432"
  env_file:
    - '.env.db'
